version: '3.1'

services:
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 13306:8080
  mysql:
    image: percona:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pa55w0rd
    ports:
      - 3306:3306
    volumes:
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/server.cnf:/etc/my.cnf.d/server.cnf:ro
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/logs:/data/log
      - ./rabbitmq/data:/data/mnesia
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis
    ports:
      - 16379:8081
